// src/features/Wallets/WalletForm.tsx
import { useEffect, useState } from "react";
import { createWallet, updateWallet, type WalletDTO, type CreateWalletCommand, type UpdateWalletCommand } from "./wallet.service";
import { notification } from "../../shared/services/notification";

type WalletFormProps = {
  wallet?: WalletDTO | null; // se null/criação, se objeto/edição
  onSuccess: () => void;
  onCancel?: () => void;
  userId: string | undefined;
};

const DEFAULT_CURRENCIES = [
  { value: "BRL", label: "Real (BRL)" },
  { value: "USD", label: "Dólar (USD)" },
  { value: "EUR", label: "Euro (EUR)" },
  // Adicione outras moedas se necessário
];

export default function WalletForm({ wallet, onSuccess, onCancel, userId }: WalletFormProps) {
  const [name, setName] = useState("");
  const [defaultCurrency, setDefaultCurrency] = useState("BRL");
  const [description, setDescription] = useState("");
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (wallet) {
      setName(wallet.name);
      setDefaultCurrency(wallet.defaultCurrency);
      setDescription(wallet.description ?? "");
    } else {
      setName("");
      setDefaultCurrency("BRL");
      setDescription("");
    }
  }, [wallet]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!name.trim()) {
      notification.error("Nome da carteira é obrigatório");
      return;
    }
    if (!defaultCurrency) {
      notification.error("Selecione a moeda padrão");
      return;
    }

    setSubmitting(true);
    try {
      if (wallet) {
        const payload: UpdateWalletCommand = {
          id: wallet.id,
          userId: wallet.userId,
          name: name.trim(),
          defaultCurrency,
          description: description.trim() || undefined,
        };
        await updateWallet(payload);
        notification.success("Carteira atualizada com sucesso!");
      } else {
        if(userId) {
            const payload: CreateWalletCommand = {
                userId,
                name: name.trim(),
                defaultCurrency,
                description: description.trim() || undefined,
            };
            await createWallet(payload);
            notification.success("Carteira criada com sucesso!");
        }
      }
      onSuccess();
      if (onCancel) onCancel();
    } catch {
      notification.error("Erro ao salvar carteira");
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-col gap-4 bg-slate-900 p-4 rounded-2xl shadow mb-8">
      <div>
        <label className="block text-white font-semibold mb-1">Nome*</label>
        <input
          className="w-full px-3 py-2 rounded bg-slate-800 text-white"
          type="text"
          value={name}
          maxLength={80}
          onChange={e => setName(e.target.value)}
          required
          disabled={submitting}
          autoFocus
        />
      </div>
      <div>
        <label className="block text-white font-semibold mb-1">Moeda*</label>
        <select
          className="w-full px-3 py-2 rounded bg-slate-800 text-white"
          value={defaultCurrency}
          onChange={e => setDefaultCurrency(e.target.value)}
          required
          disabled={submitting}
        >
          {DEFAULT_CURRENCIES.map(c => (
            <option key={c.value} value={c.value}>
              {c.label}
            </option>
          ))}
        </select>
      </div>
      <div>
        <label className="block text-white font-semibold mb-1">Descrição</label>
        <textarea
          className="w-full px-3 py-2 rounded bg-slate-800 text-white"
          value={description}
          maxLength={200}
          onChange={e => setDescription(e.target.value)}
          rows={2}
          disabled={submitting}
        />
      </div>
      <div className="flex gap-2 justify-end mt-2">
        {onCancel && (
          <button
            type="button"
            onClick={onCancel}
            className="px-4 py-2 rounded bg-slate-700 hover:bg-slate-600 text-white"
            disabled={submitting}
          >
            Cancelar
          </button>
        )}
        <button
          type="submit"
          className="px-4 py-2 rounded bg-blue-600 hover:bg-blue-700 text-white font-bold"
          disabled={submitting}
        >
          {wallet ? "Salvar alterações" : "Criar carteira"}
        </button>
      </div>
    </form>
  );
}

// src/app/features/wallets/wallet-form/wallet-form.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { WalletService } from '../../../core/services/wallet.service';
import { NotificationService } from '../../../core/services/notification.service';

@Component({
  selector: 'app-wallet-form',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './wallet-form.component.html',
  styleUrls: ['./wallet-form.component.scss'],
})
export class WalletFormComponent implements OnInit {
  form: FormGroup;
  currencies = ['BRL', 'USD', 'EUR'];
  isEditing = false;
  walletId: string | null = null;

  constructor(
    private fb: FormBuilder,
    private walletService: WalletService,
    private router: Router,
    private route: ActivatedRoute,
    private notification: NotificationService,
  ) {
    this.form = this.fb.group({
      name: ['', Validators.required],
      description: [''],
      defaultCurrency: ['', Validators.required],
    });
  }

  ngOnInit(): void {
    this.walletId = this.route.snapshot.paramMap.get('id');
    if (this.walletId) {
      this.isEditing = true;
      this.walletService.getWalletById(this.walletId).subscribe({
        next: (wallet) => {
          this.form.patchValue({
            name: wallet.name,
            description: wallet.description,
            defaultCurrency: wallet.defaultCurrency,
          });
        },
        error: () => {
          this.notification.error('Erro ao carregar carteira.');
          this.router.navigate(['/wallets']);
        },
      });
    }
  }

  submit(): void {
    if (this.form.valid) {
      const data = this.form.value;

      if (this.isEditing && this.walletId) {
        this.walletService.updateWallet(this.walletId, {
          id: this.walletId,
          ...data
        }).subscribe({
          next: () => {
            this.notification.success('Carteira atualizada com sucesso!');
            this.router.navigate(['/wallets']);
          },
          error: () => {
            this.notification.error('Erro ao atualizar carteira.');
          },
        });
      } else {
        this.walletService.createWallet(data).subscribe({
          next: () => {
            this.notification.success('Carteira criada com sucesso!');
            this.router.navigate(['/wallets']);
          },
          error: () => {
            this.notification.error('Erro ao criar carteira.');
          },
        });
      }
    } else {
      this.form.markAllAsTouched();
    }
  }

  cancel(): void {
    this.router.navigate(['/wallets']);
  }
}

<div class="container mt-4" style="max-width: 600px;">
  <form [formGroup]="form" (ngSubmit)="submit()">
    <div class="mb-3">
      <label for="name" class="form-label">Nome da Carteira</label>
      <input
        type="text"
        id="name"
        class="form-control"
        formControlName="name"
        [class.is-invalid]="form.get('name')?.touched && form.get('name')?.invalid"
      />
      @if (form.get('name')?.touched && form.get('name')?.invalid) {
        <div class="invalid-feedback">O nome é obrigatório.</div>
      }
    </div>

    <div class="mb-3">
      <label for="description" class="form-label">Descrição</label>
      <textarea id="description" class="form-control" formControlName="description"></textarea>
    </div>

    <div class="mb-3">
      <label for="defaultCurrency" class="form-label">Moeda Padrão</label>
      <select
        id="defaultCurrency"
        class="form-select"
        formControlName="defaultCurrency"
        [class.is-invalid]="form.get('defaultCurrency')?.touched && form.get('defaultCurrency')?.invalid"
      >
        <option value="">Selecione...</option>
        @for (currency of currencies; track currency) {
          <option [value]="currency">{{ currency }}</option>
        }
      </select>
      @if (form.get('defaultCurrency')?.touched && form.get('defaultCurrency')?.invalid) {
        <div class="invalid-feedback">Selecione uma moeda.</div>
      }
    </div>

    <div class="d-flex justify-content-end gap-2">
      <button type="button" class="btn btn-secondary" [disabled]="form.invalid || loading" (click)="cancel()">
        Cancelar
      </button>
      <button type="submit" class="btn btn-primary" [disabled]="form.invalid || loading">
        @if(loading) {
          <span class="spinner-border spinner-border-sm me-1"></span>
        }
        Salvar
      </button>
    </div>
  </form>
</div>
